repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--fix]
        files: ^py-backend/
      - id: ruff-format
        files: ^py-backend/

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy
        args: [app/]
        language: system
        types: [python]
        pass_filenames: false
        files: ^py-backend/

      - id: pylint
        name: pylint
        entry: uv run pylint
        args: [app/]
        language: system
        types: [python]
        pass_filenames: false
        files: ^py-backend/
